export const dummyData = [
  {
    id: 1,
    name: "Ian",
    gender: "Male",
    firstHeight: 80,
    secondHeight: 100,
  },
  {
    id: 2,
    name: "Chris",
    gender: "Male",
    firstHeight: 20,
    secondHeight: 55,
  },
  {
    id: 3,
    name: "Amanda",
    gender: "Female",
    firstHeight: 10,
    secondHeight: 35,
  },
  {
    id: 4,
    name: "Paul",
    gender: "Male",
    firstHeight: 40,
    secondHeight: 90,
  },
  {
    id: 5,
    name: "Christina",
    gender: "Female",
    firstHeight: 80,
    secondHeight: 100,
  },
  {
    id: 6,
    name: "Grace",
    gender: "Female",
    firstHeight: 30,
    secondHeight: 40,
  },
  {
    id: 7,
    name: "Angela",
    gender: "Female",
    firstHeight: 50,
    secondHeight: 65,
  },
  {
    id: 8,
    name: "Diane",
    gender: "Female",
    firstHeight: 35,
    secondHeight: 90,
  },
  {
    id: 9,
    name: "Rachel",
    gender: "Female",
    firstHeight: 70,
    secondHeight: 75,
  },
  {
    id: 10,
    name: "Jay",
    gender: "Male",
    firstHeight: 75,
    secondHeight: 100,
  },
  {
    id: 3,
    name: "David",
    gender: "Male",
    firstHeight: 25,
    secondHeight: 90,
  },
  {
    id: 2,
    name: "Bruno",
    gender: "Male",
    firstHeight: 15,
    secondHeight: 20,
  },
  {
    id: 10,
    name: "Michille",
    gender: "Female",
    firstHeight: 85,
    secondHeight: 62,
  },
  {
    id: 7,
    name: "Jasmine",
    gender: "Female",
    firstHeight: 55,
    secondHeight: 65,
  },
];
